version: '3.8'

services:
  # PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: eventbooking_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bookingService
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eventbooking_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:7-alpine
    container_name: eventbooking_redis
    ports:
      - "6379:6379"
    networks:
      - eventbooking_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # BookingService
  booking-service:
    build:
      context: ./BookingService
      dockerfile: Presentation/Dockerfile
    container_name: eventbooking_booking_service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=bookingService;Username=postgres;Password=admin;
      - ConnectionStrings__Redis=redis:6379,abortConnect=false
      - Jwt__SecretKey=supersecretkey43523452352345217865345
      - Jwt__Issuer=Users
      - Jwt__Audience=Clients
      - Jwt__ExpirationInMinutes=60
    ports:
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - eventbooking_network
    restart: unless-stopped

  # PaymentService
  payment-service:
    build:
      context: ./PaymentService
      dockerfile: Presentation/Dockerfile
    container_name: eventbooking_payment_service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5079
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=paymentService;Username=postgres;Password=admin;
    ports:
      - "5079:5079"
    depends_on:
      postgres:
        condition: service_healthy
      booking-service:
        condition: service_started
    networks:
      - eventbooking_network
    restart: unless-stopped

networks:
  eventbooking_network:
    driver: bridge

volumes:
  postgres_data: