services:
  bookingservice:
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: Host=postgresdb;Port=5432;Database=bookingservice;Username=postgres;Password=postgres;
      ConnectionStrings__Redis: redis:6379
      MessageBroker__Host: rabbitmq
      MessageBroker__User: guest
      MessageBroker__Password: guest
    ports:
      - "5070:8080"
    depends_on:
      - postgresdb
      - redis
      - rabbitmq
    networks:
      - booking-net

  paymentservice:
    image: your-registry/paymentservice:latest
    environment:
      BookingService__BaseUrl: http://bookingservice:8080
    depends_on:
      - rabbitmq
    networks:
      - booking-net

  postgresdb:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookingservice
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - booking-net

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - booking-net

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - booking-net

volumes:
  postgres-data:
  redis-data:

networks:
  booking-net:
    driver: bridge
